version: '3'
services:
  fake_auth_server:
    hostname: fake_auth
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    networks:
      - obo-backend

networks:
  obo-backend:
    name: obo-backend
    external: false
