version: '3'
services:
  fake_auth_server:
    image: ghcr.io/fredrikmorstad/fake_auth/fake_auth:latest
    hostname: fake_auth
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/fredrikmorstad/fake_auth/fake_auth:latest
    volumes:
      - ./:/app
    ports:
      - "6348:6348"
    networks:
      - obo-backend
    # env_file:
    #   - "local.env"

networks:
  obo-backend:
    name: obo-backend
    external: false
