apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: jwker
  # namespace: nais
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: jwker
  template:
    metadata:
      labels:
        control-plane: jwker
    spec:
      containers:
      - args:
        # - --storageBucket=jwker-test
        # - --port=8080
      #   - --credentialsPath=/var/run/secret/sa-credentials.json
      #   - --tokendingsUrl=https://tokendings.dev-gcp.nais.io
      #   command:
      #   - /jwker
        image: ghcr.io/fredrikmorstad/jwker/jwker:latest
        env: 
          - name: JWKER_CLIENT_ID
            value: dfb2cec9-3b6d-456b-a14f-649236247e3d
          - name: TOKENDINGS_URL
            value: http://tokendings:7456
          - name: CLUSTER_NAME
            value: kind-skiperator
          - name: JWKER_PRIVATE_JWK
            value: | 
              {"p":"-UTsojJQES7Rxg-wyiRBMwI7qyBfjiBXkhOfhwLZPvaNFnL5O4PDZOl_5RpYSKYm3zhe1sI37P8kKLXpWKGTtahPU8pJp6wi3wKa14BjHfBoUD8vC8vPR6LPzCkaksuSLxnabmCqi5BIgM4Ktt8L365wxj3XvZk78jdqkfZ5TrU","kty":"RSA","q":"97x12F8J4rdh4Fxlnu_h8-RusL4JRFfXg3NC5Xg-sCUYA8qgObHAyQpeNj6WCN10G_OxdUaRvK-0RY0eeiAK2QgIgmQBhaRUcIk1_TE7NS30L8DbsLvJUkR38YrrSlGipMgIp2p1cPH2o0qqUREu3kBHpyibMtYJhP4GTtYo73k","d":"owLjH1SbTKdgzK85s49oWGJXQ_0JZ0Gl_eYGodAXDJFRwRnCWcqmaQ4mtve8LuQKNhyfNzGL0q5B1EwzIQUTDA53OuU_nMLQREqajA7rl_EpAJaSt41AwE183Dq61BAgQvKCNBK2av_ih_eX5fZ0uwFarL4VNmP6ac-9SbOFKYWhYPksXkw9PO8PfjtVcR8mLC48LHfc-4WDZFb_7PZEGUE7LWIqfEq_LkMOx-zyB_aAENCgyjjJ00ArFpHwK6kJtuYW_vWCTUirn3V5EddFNuR9ueSo-OptOiR3U4v6zJDGdtvISP0wjLFOfyXfhy9gFOYaA9vX7O3AtXgpgG_gAQ","e":"AQAB","qi":"eDUmJ_GRtjbLzaF-bHQzIxxV7wJ8ta2Sc60yATDh1lfMOv1dKeVm5oXJIn-wz9yUVZqALyaXOXU4ajG3prAUuueoB7cVMx03AC91p3zMdTcCmhGfX3tT2VovpdrAjB7d6EtMYV5tHSsNBpkCMZQ4Gbp0oqaJFZEvCvKL_BuPKJk","dp":"baDBjcgg7J2xxrDp6M0vG5b01RtEy0YwHV-h_ofjMczPWjswn9sgWUZUaFdA0pq4Z93r3_nFDOddaMYwnTlatD8UvF4wLJ0JLRmBLhwZ-3Xa-sf_EeoN_Ix_ZWQCeuMrJKnzJi4_c2f-ax-zGKBaIYMfuCBEvO8irTFwHkfPLC0","dq":"VznI-GUGEwhkct21fg-SLBB7FMnkc2bGX-ceX7NFxzlYSkV2wrmeWmrHHyxMIVTvw8O68MLnH1tyCqcUWwWbLC1S6a4Shx6ECJeXJc3GvgOvHX03HPQRf2DSJn62N5WkwYYY3fFy5lCbeYUZkK-PI_vX_rgiZPTNp0DVsb5f7Wk","n":"8TkBrXSAMTfBCnN1eQYUk6swUGUSVkKqim2HcbQe3vBEi7hATEiChL49z1f40w2l4qEMUpgQTUigkdacAc39I7VKaZkf0573KZa-pra0BDxOWGnqQUtseK73XM6Pn4Im9EU1fqQhSBUqOAMky40aLo4u4RFmCZRCTKMAJaVzOE0aSslmW0wN2SPQfMwqcglkAcoJhqn8kejJ7kA6j8DpR1Q0CTy9hhn63DRJSKD3Lx93g9YiBCBYXYQTBH4-ZUePPk6rHJvU6g40xbfRCWOjG6SSrEOKBL-qZGxIA_MUYJpNRH1YmHl5mzp9KahCplPBSWRaCSo4n8Q_68f-WhkujQ"}

        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /jwks
        #     port: 8080
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        name: jwker
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 30Mi
        #   requests:
        #     cpu: 100m
        #     memory: 20Mi
        # volumeMounts:
        # - mountPath: /var/run/secret
        #   name: jwker-sa-credentials
        #   readOnly: true
      # terminationGracePeriodSeconds: 10
      # serviceAccount: jwker
      # serviceAccountName: jwker
      # imagePullSecrets:
      # - name: gpr-credentials
      # volumes:
      # - name: jwker-sa-credentials
      #   secret:
      #     secretName: jwker-sa-credentials
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jwker
  name: jwker
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: jwker
  name: jwker
rules:
- apiGroups:
  - '*'
  resources:
  - jwkers
  - events
  - namespaces
  - secrets
  verbs:
  - get
  - create
  - update
  - delete
  - patch
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: jwker
  name: jwker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jwker
subjects:
- kind: ServiceAccount
  name: jwker
  namespace: default
---
