apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-run-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/run/postgresql/"
