apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
metadata:
  name: some-app
spec:
  image: ghcr.io/fredrikmorstad/some_app/some_app:latest
  port: 6349
  replicas: 1
  jwker:
    - enable: true
  accessPolicy:
    outbound:
      rules:
        - application: tokendings
        - application: some-app
    inbound:
      rules:
        - application: tokendings
        - application: some-app
