version: '3'
services:
  test_app:
    hostname: test_app
    build: .
    volumes:
      - ./:/app
    ports:
      - "6000:6000"
    networks:
      - obo-backend
networks:
  obo-backend:
    name: obo-backend
    external: true
